### ISSUE TITLE
Importing CSV data overwrites all existing outcomes

### ISSUE THREAD

**Issue by srk23** [bwallace/OpenMeta-analyst-#277]
Using Openmeta 20150301 on Yosemite.

When I import CSV data, any previously created outcomes are deleted (even if a new outcome has been created to import into).

**Comment by gdietz** [comment]
@srk23 This is semi-intended. We treat importing a CSV basically like creating a new dataset from scratch.

**Comment by srk23** [comment]
So presumably there is not way of creating an oma file with multiple outcomes via csv imports?  You would therefore need a separate file for each outcome?

Simon

**Comment by gdietz** [comment]
Currently, you can only import csvs for datasets with a single outcome as you noted that existing outcomes are lost when importing a csv. However, you can copy and paste your data from excel very easily.
